In [1]:
import numpy as np

In [ ]:
# why numpy??
# To understand the difference between 1,2,3D arrays, to apply linear algebra
# and apply operations without using for-loops

# THE BASICS

In [ ]:
# In numpy dimensions are called as axes.
# Functions:

ndarray.ndim  - the number of axes of array
ndarray.shape - to know the shape of array(n,m) - (row,column)
ndarray.size - total element in array
ndarray.itemsize - size in bytes of each element
ndarray.dtype - data type of array


# Example

In [41]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.size

15

# Creating array

In [11]:
# we can also create array from regular python list or tuple using array function
a = np.array([2,3,4])
a
b = np.array([2.1,3.1,4.1])
a,b

(array([2, 3, 4]), array([2.1, 3.1, 4.1]))

In [17]:
c = np.array([(1,2,3),(4,5,6)])
c
c,c.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [20]:
#dtype of all the elemnets should be same

d = np.array([(1.5,2,3),(4,5,6)])
d
d,d.dtype

(array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]),
 dtype('float64'))

In [22]:
#converting our element to complex numbers

e = np.array([(1,2),(3,4)],dtype=complex)
e

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

# Zeros and Ones

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# linspace

In [27]:
#linspace(a,b,c)  here we can have c numbers from range of a to b

np.linspace(0,2,9)    # 9 number fro 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [30]:
pi = 3.14
f = np.linspace(0,2*pi, 100)

g = np.sin(f)
f,g

(array([0.        , 0.06343434, 0.12686869, 0.19030303, 0.25373737,
        0.31717172, 0.38060606, 0.4440404 , 0.50747475, 0.57090909,
        0.63434343, 0.69777778, 0.76121212, 0.82464646, 0.88808081,
        0.95151515, 1.01494949, 1.07838384, 1.14181818, 1.20525253,
        1.26868687, 1.33212121, 1.39555556, 1.4589899 , 1.52242424,
        1.58585859, 1.64929293, 1.71272727, 1.77616162, 1.83959596,
        1.9030303 , 1.96646465, 2.02989899, 2.09333333, 2.15676768,
        2.22020202, 2.28363636, 2.34707071, 2.41050505, 2.47393939,
        2.53737374, 2.60080808, 2.66424242, 2.72767677, 2.79111111,
        2.85454545, 2.9179798 , 2.98141414, 3.04484848, 3.10828283,
        3.17171717, 3.23515152, 3.29858586, 3.3620202 , 3.42545455,
        3.48888889, 3.55232323, 3.61575758, 3.67919192, 3.74262626,
        3.80606061, 3.86949495, 3.93292929, 3.99636364, 4.05979798,
        4.12323232, 4.18666667, 4.25010101, 4.31353535, 4.3769697 ,
        4.44040404, 4.50383838, 4.56727273, 4.63

# Basic operations

In [31]:
g = np.array([20,30,40,50])

h = np.arange(4)

g,h

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [33]:
i = g-h
i

array([20, 29, 38, 47])

In [34]:
j = np.array([[1,1],[0,1]])

k = np.array([[2,0],[3,4]])
j,k

(array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]]))

In [35]:
j*k     #elementwise product

array([[2, 0],
       [0, 4]])

In [36]:
j@k    #matrix product

array([[5, 4],
       [3, 4]])

In [37]:
j.dot(k)     #another matrix product or dot product

array([[5, 4],
       [3, 4]])

In [40]:
# Using random function
rg = np.random.default_rng(1)     #create obj of default random generator
l = rg.random((2,3))
l

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [42]:
l.sum()

3.290252281866131

In [43]:
l.min()

0.14415961271963373

In [44]:
l.max()

0.9504636963259353

In [46]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
a.sum(axis=0)                #axis = 0 :column

array([15, 18, 21, 24, 27])

In [48]:
a.sum(axis=1)               # axis = 1:row

array([10, 35, 60])

In [49]:
a.cumsum(axis=1)            #cumulative sum across rows

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [51]:
# Numpy also support universal functions such as , sqrt,exp,sin,cos...etc


m = np.arange(4)

m

array([0, 1, 2, 3])

In [52]:
np.exp(m)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [53]:
np.sqrt(m)

array([0.        , 1.        , 1.41421356, 1.73205081])

# Indexing, Slicing and iterating.

In [54]:
n = np.arange(10)**3
n

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [55]:
n[2]

8

In [56]:
n[2:5]

array([ 8, 27, 64], dtype=int32)

In [57]:
n[::2]                     #considering all the elements with a gap  of 2.

array([  0,   8,  64, 216, 512], dtype=int32)

In [58]:
#using function in numpy

def _(x,y):
    return 10*x+y

o = np.fromfunction(_,(5,4),dtype=int)
o

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [59]:
#if we want to have only elements of column 2 than,

o[0:5,1]              # consider all the rows and than go with specific column

array([ 1, 11, 21, 31, 41])

In [60]:
for _ in o.flat:
    print(_)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [61]:
o.ravel()               #return the array, flattened

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [62]:
 o.T           #return the transpose of array

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

# Stacking together different arrays

In [67]:
p = np.floor(10*rg.random((2,2)))
p

array([[3., 4.],
       [1., 4.]])

In [68]:
np.vstack((p))                        # vertically stacking

array([[3., 4.],
       [1., 4.]])

In [69]:
np.hstack((p))                        # horizontally stacking

array([3., 4., 1., 4.])

In [70]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

# Advance Numpy

In [5]:
a = [1,2,3,4,5]
b = [10,11,12,13,14]

result = []

for first,second in zip(a,b):
    result.append(first+second)

result    

[11, 13, 15, 17, 19]

In [2]:
f = np.array([11.5,12,14,13])

f.shape

(4,)

In [6]:
f.size

4

In [6]:
a =np.array(a)

In [8]:
a

array([1, 2, 3, 4, 5])

In [3]:
f = np.append(f,15)

In [17]:
f.size


5

In [7]:
f + a

array([12.5, 14. , 17. , 17. , 20. ])

In [9]:
c = np.array([[0,1,2,3],[4,5,6,7]])

c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
c.ndim

2

In [11]:
c.shape

(2, 4)

In [12]:
c.size

8

In [13]:
c[1,3]

7

In [14]:
c[1]

array([4, 5, 6, 7])

In [15]:
c[0]

array([0, 1, 2, 3])

In [16]:
c[-1]

array([4, 5, 6, 7])

In [20]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
d = np.arange(36).reshape(6,6)
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [27]:
d[0,3:5]

array([3, 4])

In [28]:
d[4:,4:]

array([[28, 29],
       [34, 35]])

In [32]:
np.vstack(d[:,2])

array([[ 2],
       [ 8],
       [14],
       [20],
       [26],
       [32]])

In [33]:
np.vstack(d[2::2,::2])

array([[12, 14, 16],
       [24, 26, 28]])

In [2]:
e = np.arange(25).reshape(5,5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
np.vstack(e[:,1::2])

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [7]:
np.vstack(e[1::2,:3:2])

array([[ 5,  7],
       [15, 17]])

In [8]:
np.hstack(e[-1:,:])

array([20, 21, 22, 23, 24])

In [9]:
f = np.array([1,2,3,4,5])
f

array([1, 2, 3, 4, 5])

In [10]:
g = f[:2]

In [11]:
g

array([1, 2])

In [12]:
g[0] = -1
g

array([-1,  2])

In [13]:
f               #here g is derived from f it is not a new data.

array([-1,  2,  3,  4,  5])

In [14]:
h = f.copy()
h
    

array([-1,  2,  3,  4,  5])

In [15]:
h[0] = 1

In [16]:
h,f                  #here we have copied the data and placed as another buffer

(array([1, 2, 3, 4, 5]), array([-1,  2,  3,  4,  5]))